/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AllChangeCollector;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner kb = new Scanner(System.in);
        
        System.out.print("Enter GIT repository URL: ");
        String url = kb.nextLine();
        System.out.print("Enter Desired directory name: ");
        String dir = kb.nextLine();
        System.out.println("\n\n");
        
        // Cloning 
        clone_repo(url);

        crawl_commit_id(dir);

        getChange();

        kb.close();
    }

    public static void clone_repo(String repo_url)
    {
        System.out.println("======    Starting Task : Cloning Repository    ========");
        Process process;
        try {
            System.out.println("Start cloning " + repo_url + ".............");
            process = Runtime.getRuntime().exec("git clone " + repo_url);
            printResult(process);
        } catch (IOException e) {
            System.out.println("Failed Cloning");
            e.printStackTrace();
        }
        
        System.out.println("Cloning Completed\n\n");
    }

    public static void crawl_commit_id(String dir)
    {
        System.out.println("===== Starting Task : Commit ID Collecting ======");
        
        ProcessBuilder processbuilder = new ProcessBuilder();
        processbuilder.command("git", "log", "--pretty=format:\"%H\"");
        String work_dir = System.getProperty("user.dir") + "/" + dir;
        System.out.println("Current working directory is " + work_dir); // DEBUG
        processbuilder.directory(new File(work_dir));

        // get history commit ids using 'git log'
        try {
            System.out.println("git log executing");
            Process process = processbuilder.start();
            saveResult(process, work_dir);
        } catch (IOException e) {
            e.printStackTrace();
        }
        System.out.println("All commit ID extracted\n\n");
    }

    public static void getChange()
    {
        
    }

    // Question: it cannot print the execution of the git cloning process, why?
    public static void printResult(Process process) throws IOException
    {
        BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
        String line = "";
        while ((line = reader.readLine()) != null) {
            System.out.println(line);
        }
        reader.close();
    }

    // saves all the commitID in the filename 'commitID.txt'
    public static void saveResult(Process process, String working_dir) throws IOException{
        File file = new File(working_dir, "commitID.txt");
        BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
        BufferedWriter writer = new BufferedWriter(new FileWriter(file));
        String line = "";
        while((line = reader.readLine()) != null){
            line = line.substring(1, line.length()-1);
            writer.write(line + "\n");
        }
        writer.close();
        reader.close();
    }
}
